name: Deploy MagicCap update
on:
  push:
    branches:
      - stable
      - beta
      - alpha

jobs:
  linux-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.17"
      - name: Install Linux development dependencies
        run: sudo apt update && sudo apt install -y libappindicator3-dev libxtst-dev libpng++-dev libxkbcommon-x11-0 xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libx11-dev
      - name: Run the build script
        run: make linux-ci
      - uses: actions/upload-artifact@v3
        with:
          name: MagicCap-3.0.0-1.amd64.rpm
          path: bundles/MagicCap-3.0.0-1.amd64.rpm
      - uses: actions/upload-artifact@v3
        with:
          name: magiccap_3.0.0_amd64.deb
          path: bundles/magiccap_3.0.0_amd64.deb
      # TODO: upload to package mirrors

  darwin-build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - uses: dcodeIO/setup-node-nvm@master
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.17"
      - name: Install Macintosh development dependencies
        run: HOMEBREW_NO_AUTO_UPODATE=1 brew install go node
      - name: Copy the certificate into the keychain
        run: build/scripts/copy_certificate.sh
        env:
          P12_DATA: ${{ env.P12_DATA }}
      - name: Run the build/deploy script
        run: make darwin-ci
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: ${{ env.S3_BUCKET }}
          S3_ENDPOINT: ${{ env.S3_ENDPOINT }}
          API_KEY: ${{ env.API_KEY }}
      - uses: actions/upload-artifact@v3
        with:
          name: MagicCap.dmg
          path: bundles/MagicCap.dmg
