name: Run MagicCap tests
on: [push]
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run yarn
        run: make yarn
      - name: Run lint
        run: make lint
